# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-02 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180402_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
